CREATE TABLE SAM_EMPLOYEE(
		NUM VARCHAR(20) NOT NULL,
		NAME VARCHAR(20),
		BIRTHDATE VARCHAR(20),
		SSN VARCHAR(20),
		SEX VARCHAR(20),
		TELEPHONE VARCHAR(20),
		ADDRESS VARCHAR(80),
		POSTAL VARCHAR(20),
		JOBLEVEL_CODE VARCHAR(20),
		DIVISION_CODE VARCHAR(20),
		DEPARTMENT_CODE VARCHAR(20),
		SKILL_CODE VARCHAR(20),
		CONSTRAINT SAM_EMPLOYEE_PK PRIMARY KEY(NUM)

);

CREATE TABLE SAM_EMPLOYEE_DLT(
		NUM VARCHAR(20) NOT NULL,
		NAME VARCHAR(20),
		BIRTHDATE VARCHAR(20),
		SSN VARCHAR(20),
		SEX VARCHAR(20),
		TELEPHONE VARCHAR(20),
		ADDRESS VARCHAR(80),
		POSTAL VARCHAR(20),
		JOBLEVEL_CODE VARCHAR(20),
		DIVISION_CODE VARCHAR(20),
		DEPARTMENT_CODE VARCHAR(20),
		SKILL_CODE VARCHAR(20),
		CONSTRAINT SAM_EMPLOYEE_DLT_PK PRIMARY KEY(NUM)
);

CREATE TABLE SAM_EMPLOYEE_MASTERDETAIL(
		NUM VARCHAR(20) NOT NULL,
		NOWJOB VARCHAR(30),
		TITLE VARCHAR(20),
		RETIREMENT VARCHAR(20),
		WORKINGYEAR VARCHAR(80),
		FIRSTDATE VARCHAR(20),
		WORKINGDATE VARCHAR(20),
		MARRIAGE VARCHAR(20),
		ARMY VARCHAR(20),
		CONSTRAINT SAM_EMPLOYEE_MASTERDETAIL_PK PRIMARY KEY(NUM)
);

CREATE TABLE SAM_EXCEL_EMPLOYEE(
		NUM VARCHAR(20) NOT NULL,
		NAME VARCHAR(20),
		BIRTHDATE VARCHAR(20),
		TELEPHONE VARCHAR(20),
		JOBLEVEL_CODE VARCHAR(20),
		SKILL_CODE VARCHAR(20),
		CONSTRAINT SAM_EXCEL_EMPLOYEE_PK PRIMARY KEY(NUM)
);

CREATE TABLE SAM_ACHIEVEMENT(
		NUM VARCHAR(20) NOT NULL,
		YYYY VARCHAR(20) NOT NULL,
		VALUE  VARCHAR(100),
		ETC VARCHAR(100),
		MM VARCHAR(20) NOT NULL
);		

CREATE TABLE SAM_CODE(
		CODE_GROUP VARCHAR(20) NOT NULL,
		CODE VARCHAR(20) NOT NULL,
		NAME VARCHAR(20),
		CODE_DESC VARCHAR(100),
		CONSTRAINT SAM_CODE_PK PRIMARY KEY(CODE_GROUP, CODE)
);

CREATE TABLE SAM_SKILL(
		CODE VARCHAR(20) NOT NULL,
		NAME VARCHAR(20)
);

CREATE TABLE SAM_JOBLEVEL(
		CODE VARCHAR(20) NOT NULL,
		NAME VARCHAR(20)
);

CREATE TABLE SAM_DIVISION(
		CODE VARCHAR(20) NOT NULL,
		NAME VARCHAR(40)
);

CREATE TABLE SAM_DEPARTMENT(
		DIV_CODE VARCHAR(20) NOT NULL,
		CODE VARCHAR(20) NOT NULL,
		NAME VARCHAR(40)
);

CREATE TABLE SAM_FILE_INFO(
		FILE_NAME VARCHAR(50) NOT NULL,
		UPLOAD_FILE_PATH VARCHAR(500) NOT NULL,
		UPLOAD_FILE_NAME VARCHAR(50),
		FILE_SIZE BIGINT,
		UPLOAD_DATE VARCHAR(20),
		CONSTRAINT SAM_FILE_INFO_PK PRIMARY KEY(FILE_NAME, UPLOAD_FILE_PATH)
);

CREATE TABLE SAM_MESSAGES(
		CODE VARCHAR(100) NOT NULL,
		LOCALE VARCHAR(20) NOT NULL,
		MESSAGE VARCHAR(100),
		ATTRIBUTE VARCHAR(2),
		PRIMARY KEY(CODE, LOCALE)
);

CREATE TABLE SAM_USER(
		USR_ID VARCHAR(30) NOT NULL PRIMARY KEY,
		USR_NM VARCHAR(100) NOT NULL,
		USR_PW VARCHAR(512) NOT NULL,
		LANG_CLCD VARCHAR(4) DEFAULT 'ko',
		ROLE VARCHAR(30) DEFAULT 'developer',
		REG_DT VARCHAR(14) DEFAULT ' ',
		CHNG_USR_ID VARCHAR(30) DEFAULT ' ',
		CHNG_DT VARCHAR(14) DEFAULT ' '
);