CREATE TABLE TDO_IDGEN (
    ID_KEY        VARCHAR2(20) PRIMARY KEY,
    ID_SEQ        NUMBER
);

CREATE TABLE TDO_ACCOUNT (
    NAME        VARCHAR2(20),
    ID          VARCHAR2(20)
);

CREATE SEQUENCE idsequence START WITH 1 INCREMENT BY 1;

INSERT INTO TDO_IDGEN VALUES('AA-01',0);
INSERT INTO TDO_ACCOUNT VALUES('TEST','id-01');
