DROP TABLE TDT_USER CASCADE CONSTRAINTS;

CREATE TABLE TDT_USER (
			USR_ID VARCHAR2(30) NOT NULL,
			USR_NM VARCHAR2(100) NOT NULL,
			USR_PW VARCHAR2(512) NOT NULL,
			LANG_CLCD VARCHAR2(4) DEFAULT 'ko',
			ROLE VARCHAR2(30)  DEFAULT 'developer',
			REG_DT VARCHAR2(14) DEFAULT ' ',
			CHNG_USR_ID VARCHAR2(30) DEFAULT ' ',
			CHNG_DT VARCHAR2(14) DEFAULT ' '
);

ALTER TABLE TDT_USER
  ADD PRIMARY KEY (USR_ID);

DROP TABLE TDT_EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE TDT_EMPLOYEE
(
  NUM             VARCHAR2(20) NOT NULL,
  NAME            VARCHAR2(20),
  BIRTHDATE       VARCHAR2(20),
  SSN             VARCHAR2(20),
  GENDER             VARCHAR2(20),
  TELEPHONE       VARCHAR2(20),
  ADDRESS         VARCHAR2(80),
  POSTAL          VARCHAR2(20),
  JOBLEVEL_CODE   VARCHAR2(20),
  DEPARTMENT_CODE VARCHAR2(20),
  SKILL_CODE      VARCHAR2(20)
);

ALTER TABLE TDT_EMPLOYEE
  ADD PRIMARY KEY (NUM);

DROP TABLE TDT_EMPLOYEE_ADDITIONAL CASCADE CONSTRAINTS;

CREATE TABLE TDT_EMPLOYEE_ADDITIONAL
(
  NUM         VARCHAR2(20) NOT NULL,
  NOWJOB      VARCHAR2(100),
  WORKINGYEAR VARCHAR2(80),
  FIRSTDATE   VARCHAR2(20),
  MARRIAGE    VARCHAR2(20),
  ARMY        VARCHAR2(20)
);

DROP TABLE TDT_ACHIEVEMENT CASCADE CONSTRAINTS;

CREATE TABLE TDT_ACHIEVEMENT
(
NUM VARCHAR(20) NOT NULL,
YYYY VARCHAR(20) NOT NULL,
VALUE INTEGER,
ETC VARCHAR(100),
MM VARCHAR(20) NOT NULL
);

ALTER TABLE TDT_ACHIEVEMENT
  ADD FOREIGN KEY (NUM)
  REFERENCES TDT_EMPLOYEE (NUM);

ALTER TABLE TDT_ACHIEVEMENT
  ADD CONSTRAINT ACHIEVEMENT_PK PRIMARY KEY (NUM, YYYY, MM);

DROP TABLE TDT_DIVISION CASCADE CONSTRAINTS;

CREATE TABLE TDT_DIVISION
(
	CODE VARCHAR(20) NOT NULL,
	NAME VARCHAR(40)
);

ALTER TABLE TDT_DIVISION
  ADD PRIMARY KEY (CODE);

DROP TABLE TDT_DEPARTMENT CASCADE CONSTRAINTS;

CREATE TABLE TDT_DEPARTMENT
(
	DIV_CODE VARCHAR2(20) NOT NULL,
	CODE VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(40)
);

ALTER TABLE TDT_DEPARTMENT
  ADD FOREIGN KEY (CODE)
  REFERENCES TDT_DIVISION (CODE);

ALTER TABLE TDT_DEPARTMENT
  ADD PRIMARY KEY(CODE,DIV_CODE)

DROP TABLE TDT_APPLY CASCADE CONSTRAINTS;

CREATE TABLE TDT_APPLY
(
  NUM             VARCHAR2(20) NOT NULL,
  NAME            VARCHAR2(20),
  BIRTHDATE       VARCHAR2(20),
  SSN             VARCHAR2(20),
  GENDER             VARCHAR2(20),
  TELEPHONE       VARCHAR2(20),
  ADDRESS         VARCHAR2(80),
  POSTAL          VARCHAR2(20),
  FILE_NAME VARCHAR2(50),
  FILE_PATH VARCHAR2(150),
  FILE_SIZE VARCHAR2(50)
);

DROP TABLE TDT_ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE TDT_ACCOUNT
(
ACC_NO VARCHAR2(12) NOT NULL,
BRANCH_CD VARCHAR2(10),
USER_NM VARCHAR2(256),
USER_ID VARCHAR2(20),
BALANCE NUMERIC,
CREATE_DT VARCHAR2(14)
);

ALTER TABLE TDT_ACCOUNT
  ADD PRIMARY KEY (ACC_NO)

DROP TABLE TDT_TRANSFER CASCADE CONSTRAINTS;

CREATE TABLE TDT_TRANSFER
(
SND_ACC_NO VARCHAR(12),
SND_USER_ID VARCHAR(20),
RCV_ACC_NO VARCHAR(12),
RCV_USER_NM VARCHAR(256),
AMOUNT NUMERIC,
BALANCE NUMERIC,
TRANSFER_DT VARCHAR(14)
);

DROP TABLE TDT_CODE CASCADE CONSTRAINTS;

CREATE TABLE TDT_CODE
(
CODE_GROUP VARCHAR(20) NOT NULL,
CODE VARCHAR(20) NOT NULL,
NAME VARCHAR(20),
CODE_DESC VARCHAR(100)
);

ALTER TABLE TDT_CODE
  ADD CONSTRAINT CODE_PK PRIMARY KEY (CODE_GROUP, CODE);


DROP TABLE DB_LOG IF EXISTS;

CREATE TABLE DB_LOG   (  
   THREAD_NAME VARCHAR(100),
   LOG_TIMESTAMP VARCHAR(14),
   MESSAGE VARCHAR(4000),
   LOGGER_NAME VARCHAR(100),
   LOG_LEVEL VARCHAR(10),
   NDC VARCHAR(100),
   START_TIME VARCHAR(14),
   CALLER_FILENAME VARCHAR(100),
   CALLER_CLASS VARCHAR(100),
   CALLER_METHOD VARCHAR(100),
   CALLER_LINE VARCHAR(10)
);

