DROP TABLE  EMPLOYEE IF EXISTS;
DROP TABLE  EMPLOYEE_OUT IF EXISTS;

CREATE TABLE EMPLOYEE
(
  NUM             VARCHAR(20) NOT NULL,
  NAME            VARCHAR(20),
  BIRTHDATE       VARCHAR(20),
  SEX             VARCHAR(20),
  TELEPHONE       VARCHAR(20),
  ADDRESS         VARCHAR(80),
  POSTAL          VARCHAR(20),
  JOBLEVEL_CODE   VARCHAR(20),
  DEPARTMENT_CODE VARCHAR(20),
  SKILL_CODE      VARCHAR(20)
);

CREATE TABLE EMPLOYEE_OUT
(
  NUM             VARCHAR(20) NOT NULL,
  NAME            VARCHAR(20),
  BIRTHDATE       VARCHAR(20),
  SEX             VARCHAR(20),
  TELEPHONE       VARCHAR(20),
  ADDRESS         VARCHAR(80),
  POSTAL          VARCHAR(20),
  JOBLEVEL_CODE   VARCHAR(20),
  DEPARTMENT_CODE VARCHAR(20),
  SKILL_CODE      VARCHAR(20)
);