CREATE TABLE DB_LOG   (  
   LOG_NUM VARCHAR(100),
   THREAD_NAME VARCHAR(100),
   LOG_TIMESTAMP TIMESTAMP,
   MESSAGE VARCHAR(4000),
   LOGGER_NAME VARCHAR(100),
   LOG_LEVEL VARCHAR(10),
   CALLER_FILENAME VARCHAR(100),
   CALLER_CLASS VARCHAR(100),
   CALLER_METHOD VARCHAR(100),
   CALLER_LINE VARCHAR(10),
   EXCEPTION VARCHAR(1000)
);

CREATE SEQUENCE logSequence START WITH 1 INCREMENT BY 1;

